<?php
namespace viablecube\viasuzen\Frontend;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Class Web_Widget
 *
 * Handles injection of the web widget script on the frontend based on settings.
 *
 * @package viablecube\viasuzen\Frontend
 */
class Web_Widget {

    /**
     * Web_Widget constructor.
     *
     * Hooks into wp_enqueue_scripts to conditionally inject the widget script.
     *
     * @return void
     */
    public function __construct() {
        add_action( 'wp_enqueue_scripts', array( $this, 'inject_widget' ) );

    }

    /**
     * Inject the widget JavaScript code inline if enabled in settings.
     *
     * Checks for 'zcw_settings' option, verifies if display is set to 'auto'
     * and widget code is not empty, then registers and enqueues a dummy script handle,
     * and adds the widget code as inline script.
     *
     * @return void
	 * @author Ahsan
	 * @since  1.0.0
     */
    public function inject_widget() {

        $settings = get_option( 'viasuzen_settings' );
        $viasuzen_authorization_status = get_option( 'viasuzen_authorization_status' );

        if (
            isset( $settings['webwidget_display'] ) &&
            $settings['webwidget_display'] === 'auto' &&
            ! empty( $settings['widget_code'] ) && $viasuzen_authorization_status == '1'
        ) {
            // Sanitize widget code before output
            $js_code = $this->sanitize_widget_code_output( $settings['widget_code'] );
            
            if ( empty( $js_code ) ) {
                return;
            }
			
            wp_register_script(
                'zc-webwidget-inline',
                false,
                array(),
                VIASUZEN_VERSION,
                true
            );

            wp_enqueue_script( 'zc-webwidget-inline' );
            
            wp_add_inline_script( 'zc-webwidget-inline', $js_code );
        }
    }

    /**
     * Sanitize widget code for safe output in inline script.
     *
     * Only removes closing script tags that could break out of inline script context.
     * The widget code is auto-generated by the plugin, so minimal sanitization is needed.
     *
     * @param string $code The widget code to sanitize.
     * @return string Sanitized widget code.
     * @since 1.1.0
     */
    private function sanitize_widget_code_output( $code ) {
        if ( empty( $code ) ) {
            return '';
        }

        // Decode HTML entities that may have been encoded when stored/retrieved
        // This fixes issues like &amp;&amp; being converted back to &&
        $code = html_entity_decode( $code, ENT_QUOTES | ENT_HTML5, 'UTF-8' );
        
        // Only remove closing script tags that could break out of inline script
        // This is the main security concern - preventing XSS via script tag injection
        // Use case-insensitive replacement to catch all variations
        $code = preg_replace( '/<\/script>/i', '', $code );
        $code = preg_replace( '/<\\/script>/i', '', $code ); // Escaped version
        
        // Remove opening script tags if any (shouldn't be in inline code, but safety check)
        $code = preg_replace( '/<script[^>]*>/i', '', $code );
        
        return trim( $code );
    }
}